### ISSUE TITLE
Testing iptables checkpoint

### ISSUE THREAD

**Issue by hongchaodeng** [coreos/kenc#31]
Attack plan:
- [x] Run `kenc` as static pod on one specific node
  - priviledged mode to run `iptables`, write to `hostPath` volume
  - `hostNetwork=true` to save global iptables
  - mount hostPath volume to persist state
- [x] Create nginx pod, then create a service point to it
  - verify nginx pod isn't running on same node as kenc
  - curl service IP on node
- [ ] Shutdown control plane (esp. apiserver); then restart the worker node which kenc was running on; then check if nginx service is available.

**Comment by hongchaodeng** [comment]
Done

cc @aaronlevy @xiang90

**Comment by hongchaodeng** [comment]
Not working with another try.

**Comment by hongchaodeng** [comment]
Found root:
Init container would only run once for entire lifecycle.

**Comment by xiang90** [comment]
@hongchaodeng 

@yifan-gu believes this is a bug in 1.5.3. Can you try with kube 1.6?

**Comment by hongchaodeng** [comment]
Definitely.
But we are testing bootkube with 1.5 . We still need to fix that.

**Comment by xiang90** [comment]
@hongchaodeng Let's try 1.6. we can work this around in 1.5 by running it as a normal container.

**Comment by hongchaodeng** [comment]
Offline conclusion. Not going to test 1.6 atm.
After change to always recover, verified that it worked.
