### ISSUE TITLE
iptables-restore with no flush leads to duplicate rules

### ISSUE THREAD

**Issue by diegs** [coreos/kenc#42]
When run with `r=true`, the first think kenc does is restore rules from the checkpointed file using `iptables-restore --noflush`:

https://github.com/coreos/kenc/blob/master/main.go#L130
https://github.com/coreos/kenc/blob/master/pkg/util/iptables/iptables.go#L320

Then it starts checkpointing rules.

The problem with this approach is that the kubelet also creates its own rules by default, which are then checkpointed by kenc:

https://github.com/kubernetes/kubernetes/blob/0dff56b4d88ec7551084bf89028dbeebf569620e/pkg/kubelet/kubelet_network.go#L289

The kubelet will certainly start up before kenc does. This means that on every system reboot and kenc pod restart:

1. kubelet has added a rule `A`
2. checkpointer restores checkpoint that contains rule `A`, so now there are duplicate rules `A` `A`
3. checkpointer checkpoints `A` `A` into its checkpoint file

If there are many kenc restarts or perhaps other iptables issues then this leads to linear rule growth. In a degenerate case (not sure exactly how) I ended up with a 26mb iptables ruleset with 100,000s of copies of rules like:

```
-A PREROUTING -m comment --comment "kubernetes service portals" -j KUBE-SERVICES
-A POSTROUTING -m comment --comment "kubernetes postrouting rules" -j KUBE-POSTROUTING
```

A better approach would be to be more selective about what is checkpointed, or better yet, to use the `EnsureChain` / `EnsureRule` logic that the kubelet uses instead of invoking `iptables-restore`

**Comment by xiang90** [comment]
@diegs 

kenc code tries to simulate the kube-proxy logic, where we put all rules in one transaction and restore it with noflush. We do not need to do ensureRule or ensureChain when we try to flush out the chains anyway.

The problem is we accidentally checkpointed rules that are not inside the chains that we will flush in the restore logic. Only the rules not in the chains we flushed are duplicated.

**Comment by xiang90** [comment]
@diegs if you still keep the huge file, probably you can help me to double check that only rules in 
these chains:
```
PREROUTING
INPUT
OUTPUT
POSTROUTING
```

are duplicated and nothing else gets duplicated.

**Comment by diegs** [comment]
Here's the massive file.

[ipt.save.gz](https://github.com/coreos/kenc/files/1163359/ipt.save.gz)

**Comment by xiang90** [comment]
@diegs Checked the file. Confirmed my pervious assumption.
